var colors = require('colors/safe');
console.log(colors.black('Hello'));
console.log(colors.red('My'));
console.log(colors.green('Name'));
console.log(colors.yellow('is'));
console.log(colors.blue('MiSun (Korean name)'));
console.log(colors.magenta('And'));
console.log(colors.cyan('Friends'));
console.log(colors.white('Call me'));
console.log(colors.gray('Nika (Russian name)'));